import sampleimg from "../../assests/png/sampleimg.png";
import logo from "../../assests/png/clogo.png";

const InvestorsData = [
  {
    id: 1,
    image: sampleimg,
    brief: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut eros, ligula.",
    logo: logo,
    href: "https://en.wikipedia.org/wiki/Sean_Parker",
    title: "Sean Parker",
    type: "Artificial Intelligence",
    description:
      "Sean Parker, Intersted in Artificial Intelligence an American entrepreneur, co-founded Napster and served as Facebook's first president, Intersted in Artificial Intelligence an American entrepreneur, co-founded Napster and served as Facebook's first president.",
    linkedin: "https://linkedin.com",
    facebook: "https://facebook.com",
    twitter: "https://twitter.com",
  },
  {
    id: 2,
    image: sampleimg,
    brief: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut eros, ligula.",
    logo: logo,
    href: "https://en.wikipedia.org/wiki/Sean_Parker",
    title: "Wisdom",
    type: "Food",
    description:
      "Wisdom A Food Lover, an American entrepreneur, co-founded Napster and served as Facebook's first president, Intersted in Artificial Intelligence an American entrepreneur, co-founded Napster and served as Facebook's first president.",
    linkedin: "https://linkedin.com",
    facebook: "https://facebook.com",
    twitter: "https://twitter.com",
  },
  {
    id: 3,
    image: sampleimg,
    brief: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut eros, ligula.",
    logo: logo,
    href: "https://en.wikipedia.org/wiki/Sean_Parker",
    title: "Sean Parker",
    type: "Artificial Intelligence",
    description:
      "Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president, Intersted in Artificial Intelligence an American entrepreneur, co-founded Napster and served as Facebook's first president.",
    linkedin: "https://linkedin.com",
    facebook: "https://facebook.com",
    twitter: "https://twitter.com",
  },
  {
    id: 4,
    image: sampleimg,
    brief: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut eros, ligula.",
    logo: logo,
    href: "https://en.wikipedia.org/wiki/Sean_Parker",
    title: "Sean Parker",
    type: "Technology",
    description:
      "Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.",
    linkedin: "https://linkedin.com",
    facebook: "https://facebook.com",
    twitter: "https://twitter.com",
  },
  {
    id: 5,
    image: sampleimg,
    brief: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut eros, ligula.",
    logo: logo,
    href: "https://en.wikipedia.org/wiki/Sean_Parker",
    title: "Sean Parker",
    type: "Artificial Intelligence",
    description:
      "Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.",
    linkedin: "https://linkedin.com",
    facebook: "https://facebook.com",
    twitter: "https://twitter.com",
  },
  {
    id: 6,
    image: sampleimg,
    brief: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut eros, ligula.",
    logo: logo,
    href: "https://en.wikipedia.org/wiki/Sean_Parker",
    title: "Sean Parker",
    type: "Artificial Intelligence",
    description:
      "Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.",
    linkedin: "https://linkedin.com",
    facebook: "https://facebook.com",
    twitter: "https://twitter.com",
  },
  {
    id: 7,
    image: sampleimg,
    brief: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut eros, ligula.",
    logo: logo,
    href: "https://en.wikipedia.org/wiki/Sean_Parker",
    title: "Sean Parker",
    type: "Artificial Intelligence",
    description:
      "Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.",
    linkedin: "https://linkedin.com",
    facebook: "https://facebook.com",
    twitter: "https://twitter.com",
  },
  {
    id: 8,
    image: sampleimg,
    brief: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut eros, ligula.",
    logo: logo,
    href: "https://en.wikipedia.org/wiki/Sean_Parker",
    title: "Sean Parker",
    type: "Artificial Intelligence",
    description:
      "Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.",
    linkedin: "https://linkedin.com",
    facebook: "https://facebook.com",
    twitter: "https://twitter.com",
  },
  {
    id: 9,
    image: sampleimg,
    brief: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut eros, ligula.",
    logo: logo,
    href: "https://en.wikipedia.org/wiki/Sean_Parker",
    title: "Sean Parker",
    type: "Artificial Intelligence",
    description:
      "Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.",
    linkedin: "https://linkedin.com",
    facebook: "https://facebook.com",
    twitter: "https://twitter.com",
  },
];

export default InvestorsData;
