import samplecom from "../../assests/png/samplecom.png";
import logo from "../../assests/png/clogo.png";

const StartupsData = [
  {
    id: 1,
    image: samplecom,
    brief: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut eros, ligula.",
    logo: logo,
    type: "Artificial Intelligence",
    href: "https://en.wikipedia.org/wiki/Sean_Parker",
    title: "Reo Techs",
    description:
      "Reo Techs, an American Company, co-founded Napster and served as Facebook's first president. Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.",
    linkedin: "https://linkedin.com",
    facebook: "https://facebook.com",
    twitter: "https://twitter.com",
  },
  {
    id: 2,
    image: samplecom,
    brief: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut eros, ligula.",
    logo: logo,
    type: "Construction",
    href: "https://en.wikipedia.org/wiki/Sean_Parker",
    title: "Smart Logs",
    description:
      "Smart Logs, an American startup, co-founded Napster and served as Facebook's first president. Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.",
    linkedin: "https://linkedin.com",
    facebook: "https://facebook.com",
    twitter: "https://twitter.com",
  },
  {
    id: 3,
    image: samplecom,
    brief: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut eros, ligula.",
    logo: logo,
    type: "Healthcare",
    href: "https://en.wikipedia.org/wiki/Sean_Parker",
    title: "Chicken Chicks",
    description:
      "Chicken Chicks, an American food chain, co-founded Napster and served as Facebook's first president. Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.",
    linkedin: "https://linkedin.com",
    facebook: "https://facebook.com",
    twitter: "https://twitter.com",
  },
  {
    id: 4,
    image: samplecom,
    brief: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut eros, ligula.",
    logo: logo,
    type: "Enterprise Tech",
    href: "https://en.wikipedia.org/wiki/Sean_Parker",
    title: "Burger King",
    description:
      "Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.",
    linkedin: "https://linkedin.com",
    facebook: "https://facebook.com",
    twitter: "https://twitter.com",
  },
  {
    id: 5,
    image: samplecom,
    brief: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut eros, ligula.",
    logo: logo,
    type: "E-commerce",
    href: "https://en.wikipedia.org/wiki/Sean_Parker",
    title: "KFC",
    description:
      "Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.",
    linkedin: "https://linkedin.com",
    facebook: "https://facebook.com",
    twitter: "https://twitter.com",
  },
  {
    id: 6,
    image: samplecom,
    brief: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut eros, ligula.",
    logo: logo,
    type: "Cyber Security",
    href: "https://en.wikipedia.org/wiki/Sean_Parker",
    title: "Facesmart",
    description:
      "Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.",
    linkedin: "https://linkedin.com",
    facebook: "https://facebook.com",
    twitter: "https://twitter.com",
  },
  {
    id: 7,
    image: samplecom,
    brief: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut eros, ligula.",
    logo: logo,
    type: "Hospitality",
    href: "https://en.wikipedia.org/wiki/Sean_Parker",
    title: "McDonalds",
    description:
      "Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.",
    linkedin: "https://linkedin.com",
    facebook: "https://facebook.com",
    twitter: "https://twitter.com",
  },
  {
    id: 8,
    image: samplecom,
    brief: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut eros, ligula.",
    logo: logo,
    type: "Contraction",
    href: "https://en.wikipedia.org/wiki/Sean_Parker",
    title: "Fiverr",
    description:
      "Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.",
    linkedin: "https://linkedin.com",
    facebook: "https://facebook.com",
    twitter: "https://twitter.com",
  },
  {
    id: 9,
    image: samplecom,
    brief: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut eros, ligula.",
    logo: logo,
    type: "Tourism",
    href: "https://en.wikipedia.org/wiki/Sean_Parker",
    title: "AL Camino",
    description:
      "Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.",
    linkedin: "https://linkedin.com",
    facebook: "https://facebook.com",
    twitter: "https://twitter.com",
  },
  {
    id: 10,
    image: samplecom,
    brief: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut eros, ligula.",
    logo: logo,
    type: "Software Development",
    href: "https://en.wikipedia.org/wiki/Sean_Parker",
    title: "El Rolls",
    description:
      "Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.",
    linkedin: "https://linkedin.com",
    facebook: "https://facebook.com",
    twitter: "https://twitter.com",
  },
  {
    id: 11,
    image: samplecom,
    brief: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut eros, ligula.",
    logo: logo,
    type: "Fintech",
    href: "https://en.wikipedia.org/wiki/Sean_Parker",
    title: "El Rolls",
    description:
      "Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.",
    linkedin: "https://linkedin.com",
    facebook: "https://facebook.com",
    twitter: "https://twitter.com",
  },
  {
    id: 12,
    image: samplecom,
    brief: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut eros, ligula.",
    logo: logo,
    type: "Health & Wellness",
    href: "https://en.wikipedia.org/wiki/Sean_Parker",
    title: "El Rolls",
    description:
      "Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.",
    linkedin: "https://linkedin.com",
    facebook: "https://facebook.com",
    twitter: "https://twitter.com",
  },
  {
    id: 13,
    image: samplecom,
    brief: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut eros, ligula.",
    logo: logo,
    type: "Entertainment",
    href: "https://en.wikipedia.org/wiki/Sean_Parker",
    title: "AL Camino",
    description:
      "Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.",
    linkedin: "https://linkedin.com",
    facebook: "https://facebook.com",
    twitter: "https://twitter.com",
  },
  {
    id: 14,
    image: samplecom,
    brief: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut eros, ligula.",
    logo: logo,
    type: "Transport & Delivery",
    href: "https://en.wikipedia.org/wiki/Sean_Parker",
    title: "AL Camino",
    description:
      "Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.",
    linkedin: "https://linkedin.com",
    facebook: "https://facebook.com",
    twitter: "https://twitter.com",
  },
  {
    id: 15,
    image: samplecom,
    brief: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut eros, ligula.",
    logo: logo,
    type: "Artificial Intelligence",
    href: "https://en.wikipedia.org/wiki/Sean_Parker",
    title: "Reo Techs",
    description:
      "Reo Techs, an American Company, co-founded Napster and served as Facebook's first president. Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.",
    linkedin: "https://linkedin.com",
    facebook: "https://facebook.com",
    twitter: "https://twitter.com",
  },
  {
    id: 16,
    image: samplecom,
    brief: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut eros, ligula.",
    logo: logo,
    type: "Healthcare",
    href: "https://en.wikipedia.org/wiki/Sean_Parker",
    title: "Reo Techs",
    description:
      "Reo Techs, an American Company, co-founded Napster and served as Facebook's first president. Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.Sean Parker, an American entrepreneur, co-founded Napster and served as Facebook's first president.",
    linkedin: "https://linkedin.com",
    facebook: "https://facebook.com",
    twitter: "https://twitter.com",
  },
];

export default StartupsData;
